### ISSUE TITLE
BOM for the PyBadge / EdgeBadge?

### ISSUE THREAD

**Issue by technobly** [adafruit/Adafruit-PyBadge-PCB#2]
> README.md:
>
> 8 x Game/Control Buttons with nice silicone button tops (these feel great)

I'm looking for the tactile switches used on these badges, they do indeed feel great!

Is there a BOM for these with the part number, or any hints on where to get these?  I did find some at Digi-key, but not quite the same. https://forums.adafruit.com/viewtopic.php?p=981850#p981850

**Comment by ladyada** [comment]
our part is [LAXXSCOM 8EBB-C-B-S9-03-5](https://item.taobao.com/item.htm?id=42173630988), admittedly not available anywhere easily
can you use something like https://www.adafruit.com/product/3983 instead? they are available on aliexpress and such

**Comment by technobly** [comment]
Thanks for the info, and I'll check out that other button as well!

**Comment by technobly** [comment]
@ladyada it seems that LAXXSCOM part might be something else?  Don't see a rubber switch option here and they claim they don't make one with a silicone top:
![Screen Shot 2023-08-09 at 7 41 51 PM](https://github.com/adafruit/Adafruit-PyBadge-PCB/assets/2249224/60431a3b-4480-4fee-9e8c-32d677d0daa8)

However I found the second one at LCSC which is nice.  

I wish you carried that EdgeBadge button in your store in SMT format.  I do see you have it in TH: https://www.adafruit.com/product/4183

If you come across the part number, please let me know ;-)  TIA!

**Comment by ladyada** [comment]
here is a link https://item.taobao.com/item.htm?id=554110427268
i am not sure lcsc stocks it

**Comment by technobly** [comment]
That looks like the right one, thank you very much :D
